[platformio]
src_dir = kernel

[env:esp32-s3-dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.partitions = partitions.csv
board_build.psram = enable
board_build.psram_mode = octal

board_upload.flash_size = 16MB

build_flags =
    -D ELF_ECHO_DATA
    -D ELF_HELLO_DATA
    -D ELF_DATE_DATA
    -D ELF_FREE_DATA
    -D ELF_UNAME_DATA
    -D ELF_DF_DATA
